baseURL: "https://afaiyaz.me"
languageCode: "en-us"
title: "Faiyaz"
theme: hugo-profile
themesdir : "themes"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
   main:
    - identifier: "garden"
      name: "Blog"
      title: "Blog posts"
      url: "/garden"
   #   weight: 1
   # - identifier: gallery
   #   name: Gallery
   #   title: Blog posts
   #   url: /gallery
   #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ahmed Faiyaz"
  description: This is my portfolio website.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  #color:
  #  textColor: "dark"
  #  secondaryTextColor: "dark" 
  #  backgroundColor: "white"
  #  secondaryBackgroundColor: "off-white"
  #  primaryColor: "green"
  #  secondaryColor: "off-white"

    # darkmode:
    #   textColor:
    #   secondaryTextColor:
    #   backgroundColor:
    #   secondaryBackgroundColor:
    #   primaryColor:
    #   secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Faiyaz's World" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ahmed Faiyaz."
    subtitle: "I am a CSE graduate, programmer and amatuer researcher."
    content: "I devise solutions to problems through lateral thinking."
    image: /images_/me.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://www.linkedin.com/in/ahmed-faiyaz-951797197/"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/afaiyaz006

      customIcons:
        - icon: /fav.png
          url: "https://afaiyaz.me"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images_/me.jpg"
    content: |-
      🎓 Recent Computer Science graduate passionate about technology and coding.

      💼 Currently exploring opportunities and working on personal projects.

      🚀 I enjoy turning ideas into reality through clean and efficient code.
    skills:
      enable: true
      title: "Technologies I've been working with :"
      items:
        - "python"
        - "pytorch"
        - "sklearn"
        - "tensorflow"
        - "c"
        - "c++"
        - "Java"
        - "javascript"
        - "HTML"
        - "CSS"
        - "nextjs"
        - "react"
        - "tailwind css"
        
        

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Internship"
        company: "Quantigo AI"
        companyUrl: "https://quantigo.ai"
        date: "Jun 2024 - Aug 2024"
        content: "Worked as a engineering intern for 3 months."    
    
 
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science-BS,Computer Science"
        school:
          name: "University of Asia Pacific"
          url: "https://www.uap-bd.edu/"
        date: "2019 - 2023"
        content: |-
          I co-authored one paper in IEEE Access vol 12.
            - Okkhor-Diffusion: Class Guided Generation of Bangla Isolated Handwritten Characters Using Denoising Diffusion Probabilistic Model (DDPM)<br>
              URL : [Journal Article](https://ieeexplore.ieee.org/document/10445466) 
          I authored another paper related to a dataset.
            - Indic-Dialogue: A dataset of subtitles in 10 Indic languages for Indic language modeling.
              URL: [Journal Article](https://www.sciencedirect.com/science/article/pii/S2352340924006577)
      
 
  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: Intra University Programming Contest, UAP 2022
        content: 2nd Runner Up.
 
      - title: Hackathon - 5th Inter Department Software & Hardware Carnival 2022
        content: Champion.
 

 
  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Artnet
        content: Artnet is a photo sharing social network with a simple twist,it transforms photos into artwork based on user given style and also styles from famous artwork
        image: /images_/Artnet.png

        badges:
          - "python"
          - "Django"
          - "HTMX"
          - "CSS"
          - "javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/afaiyaz006/artnet
      - title: Mangomedia
        content: MangoMedia is a lightweight, user-friendly microblogging platform that allows users to share short posts, interact with others, and engage in real-time discussions.
        featured:
          name: Live
          link: mangomedia.vercel.app 
        badges:
          - "python"
          - "Django"
          - "HTMX"
          - "CSS"
          - "javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/afaiyaz006/Mangomedia
       - title: Kotha 
         content: This project is a lightweight, real-time chat application built using Next.js for the frontend and Socket.IO for real-time communication.
         featured:
          name: Live
          link: kotha-kappa.vercel.app
         badges:
          - "Typescript"
          - "nodejs"
          - "nextjs"
          - "tailwindcss"
          - "socket.io"
         links:
          - icon: fab fa-github
            url: https://github.com/afaiyaz006/Kotha
       # links:
       #  - icon: fa fa-envelope
       #     url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
       #   - icon: fab fa-github
       #     url: https://github.com/gurusabarish/hugo-profile
       #   - icon: fab fa-twitter
       #     url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile
      - title: Note-Write
        content: Note writing web app with some ai based features.
        image: /images_/note-write.png
        featured:
          name: Live
          link: https://note-write.vercel.app/
        badges:
          - "Typescript"
          - "nodejs"
          - "nextjs"
          - "tailwindcss"
          - "daisyui"
        links:
          - icon: fab fa-github
            url: https://github.com/afaiyaz006/note-write
      - title: UAP Bazar
        content: A simple offline store management app for desktop made with javafx.
        image: /images_/uap_bazar.png

        badges:
          - "java"
          - "javafx"
        links:
          - icon: fab fa-github
            url: https://github.com/afaiyaz006/UAPBAZAR

      - title: Cave trouble
        content: Cave trouble is an infinite side view shoot em up game.
        image: /images_/cave-trouble.png

        badges:
          - "Unity"
          - "C#"
        links:
          - icon: fab fa-github
            url: https://github.com/afaiyaz006/Cave-Trouble         
  #Contact
  contact:
    enable: false
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: 
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/afaiyaz006
      linkedin: https://www.linkedin.com/in/ahmed-faiyaz-951797197/
      facebook: https://facebook.com/a.faiyaz006

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
